version: '3.8'

services:
  # Production AIFS Server
  aifs-prod:
    image: uriber/aifs:latest
    container_name: aifs-production
    ports:
      - "50051:50051"
    volumes:
      - aifs-prod-data:/data/aifs
    environment:
      - AIFS_MODE=production
      - AIFS_HOST=0.0.0.0
      - AIFS_PORT=50051
      - AIFS_STORAGE_DIR=/data/aifs
      - AIFS_MAX_WORKERS=10
      - AIFS_COMPRESSION_LEVEL=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Development AIFS Server (with gRPC reflection)
  aifs-dev:
    image: uriber/aifs:latest
    container_name: aifs-development
    ports:
      - "50052:50051"  # Different port to avoid conflict
    volumes:
      - aifs-dev-data:/data/aifs
    environment:
      - AIFS_MODE=development
      - AIFS_HOST=0.0.0.0
      - AIFS_PORT=50051
      - AIFS_STORAGE_DIR=/data/aifs
      - AIFS_MAX_WORKERS=5
      - AIFS_COMPRESSION_LEVEL=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  aifs-prod-data:
    driver: local
  aifs-dev-data:
    driver: local