# github_pr.py
import os, subprocess, uuid, pathlib, git
from github import Github
from langchain.tools import tool


REPO = git.Repo(pathlib.Path(__file__).resolve().parents[3])
GH_TOKEN = os.environ["GITHUB_TOKEN"]
GH = Github(GH_TOKEN)
OWNER, NAME = REPO.remotes.origin.url.split(":")[1].rstrip(".git").split("/", 1)

@tool("git_push", return_direct=True)
def git_push() -> str:
    """Create a new branch, commit staged files and push to origin."""
    branch = f"bot/{uuid.uuid4().hex[:8]}"
    REPO.git.checkout("-B", branch)
    REPO.git.commit("--allow-empty", "-m", "bot: commit from crew")
    REPO.git.push("origin", branch)
    return branch

@tool("github_pr", return_direct=True)
def github_pr(branch: str) -> str:
    """Open a pull request from the given branch to main and return URL."""
    repo = GH.get_repo(f"{OWNER}/{NAME}")
    pr = repo.create_pull(
        title=f"AIFS auto-PR {branch}",
        body="Generated by CrewAI pipeline.",
        head=branch,
        base="main"
    )
    return f"Opened PR {pr.html_url}"